### Hi there, I'm Vaibhav Parikh  ğŸ‘‹
<p align="center">
  <a href="https://github.com/DenverCoder1/readme-typing-svg"><img src="https://readme-typing-svg.herokuapp.com/?lines=Full-stack%20web%20developer;Competitive%20programmer;Always%20learning%20new%20things&font=Fira%20Code&center=true&width=440&height=45&color=f75c7e&vCenter=true&size=22"></a>
</p>

- ğŸ“« How to reach me **parikhvaibhav19@gmail.com**
- ğŸ‘©â€ğŸ’» I am working on MERN stack
- ğŸš€ Resume <a href="https://drive.google.com/file/d/1HbL184oAz8nils52ZcYK0b6DCS1M6_Vn/view?usp=sharing">link</a>

- [x] ğŸŒ Web: Javascript, Node.js, Express, React, HTML, CSS 
- [x] ğŸ›’ Database: SQL(MySQL, POSTGRES), NoSQL(MongoDB, Firebase)
- [x] ğŸ‘©â€ğŸ’» Others: .Net, Github
- [x] ğŸ’» Languages: C++, Python

<h3 align="left">Connect with me:</h3>
<p align="left">
<a href="https://www.linkedin.com/in/vaibhav-parikh-9b13b61a3/" target="blank"><img align="center" src="https://img.shields.io/badge/LinkedIn-0077B5?style=for-the-badge&logo=linkedin&logoColor=white" alt="https://www.linkedin.com/in/vaibhav-parikh-9b13b61a3/" /></a> <a href="https://www.linkedin.com/in/vaibhav-parikh-9b13b61a3/" target="blank"><img align="center" src="https://img.shields.io/badge/CodeChef-%23964B00.svg?style=for-the-badge&logo=CodeChef&logoColor=white" alt="https://www.linkedin.com/in/vaibhav-parikh-9b13b61a3/" /></a> <a href="https://www.linkedin.com/in/vaibhav-parikh-9b13b61a3/" target="blank"><img align="center" src="https://img.shields.io/badge/LeetCode-000000?style=for-the-badge&logo=LeetCode&logoColor=#d16c06" /></a>
</p>

<h3 align="left">Languages and Tools:</h3>
<p align="left"> <a href="https://www.cprogramming.com/" target="_blank"> <img src="https://img.shields.io/badge/C-00599C?style=for-the-badge&logo=c&logoColor=white" alt="c" /> </a> <a href="https://www.w3schools.com/cpp/" target="_blank"> <img src="https://img.shields.io/badge/C%2B%2B-00599C?style=for-the-badge&logo=c%2B%2B&logoColor=white" alt="cplusplus" /> </a> <a href="html"
target="_blank"> <img src="https://img.shields.io/badge/HTML5-E34F26?style=for-the-badge&logo=html5&logoColor=white" alt="html" /> </a>  <a href="javascript" target="_blank"> <img src="https://img.shields.io/badge/JavaScript-323330?style=for-the-badge&logo=javascript&logoColor=F7DF1E" alt="javascript" /> </a> <a href="" target="_blank"> <img src="https://img.shields.io/badge/Node.js-339933?style=for-the-badge&logo=nodedotjs&logoColor=white" alt="c" /> </a> <a href="" target="_blank"> <img src="https://img.shields.io/badge/npm-CB3837?style=for-the-badge&logo=npm&logoColor=white" alt="cplusplus" /> </a> <a href="html"
target="_blank"> <img src="https://img.shields.io/badge/Python-FFD43B?style=for-the-badge&logo=python&logoColor=blue" alt="html" /> </a>  <a href="javascript" target="_blank"> <img src="https://img.shields.io/badge/MySQL-005C84?style=for-the-badge&logo=mysql&logoColor=white" alt="javascript" /> </a>  <a href="html" target="_blank"> <img src="https://img.shields.io/badge/PostgreSQL-316192?style=for-the-badge&logo=postgresql&logoColor=white" alt="html" /> </a>   <a href="html" target="_blank"> <img src="https://img.shields.io/badge/django-%23092E20.svg?style=for-the-badge&logo=django&logoColor=white" alt="html" /> </a>  <a href="javascript" target="_blank"> <img src="https://img.shields.io/badge/bootstrap-%23563D7C.svg?style=for-the-badge&logo=bootstrap&logoColor=white" alt="javascript" /> </a>   <a href="javascript" target="_blank"> <img src="https://img.shields.io/badge/MUI-%230081CB.svg?style=for-the-badge&logo=mui&logoColor=white" alt="javascript" /> </a> <a href="html" target="_blank"> <img src="https://img.shields.io/badge/express.js-%23404d59.svg?style=for-the-badge&logo=express&logoColor=%2361DAFB" alt="html" /> </a>  <a href="javascript" target="_blank"> <img src="https://img.shields.io/badge/heroku-%23430098.svg?style=for-the-badge&logo=heroku&logoColor=white" alt="javascript" /> </a> <a href="html" target="_blank"> <img src="https://img.shields.io/badge/docker-%230db7ed.svg?style=for-the-badge&logo=docker&logoColor=white" alt="html" /> </a>  <a href="javascript" target="_blank"> <img src="https://img.shields.io/badge/Postman-FF6C37?style=for-the-badge&logo=postman&logoColor=white" alt="javascript" /> </a>
<a href="" target="_blank"> <img src="https://img.shields.io/badge/MongoDB-4EA94B?style=for-the-badge&logo=mongodb&logoColor=white" alt="c" /> </a>
</p>

<p>&nbsp;<img align="center" src="https://github-readme-stats.vercel.app/api?username=vaibhav720&show_icons=true&locale=en&theme=radical" alt="Vaibhav720" /></p><br>


<p><img align="center" src="https://github-readme-streak-stats.herokuapp.com/?user=vaibhav720&theme=radical" alt="vaibhav720" /></p>

<br/>
<br/>

![ğšğš’ğšğš‘ğšğš‹ ğšğš›ğšŠğš™ğš‘](https://activity-graph.herokuapp.com/graph?username=vaibhav720&theme=react-dark&hide_border=true&area=true)

<br/>
<br/>
  <a href="https://github.com/vaibhav720">
    <img align="center" height="195px" src="https://github-readme-stats.vercel.app/api/top-langs/?username=vaibhav720&theme=radical&langs_count=15&layout=compact" />
  </a>
<br/>


  ![](https://komarev.com/ghpvc/?username=vaibhav720&style=for-the-badge)
